name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup bun v2
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: bun release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  docs:
    permissions:
      id-token: "write"
      pages: "write"
    name: Docs
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup bun v2
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install
      
      - name: "Build repo"
        run: bun run build

      - name: "Build documentation"
        run: bun build:docs

      - name: "Upload Pages artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          name: github-pages
          path: docs/

      - id: "deployment"
        name: "Deploy documentation to GitHub Pages"
        uses: "actions/deploy-pages@v4"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup bun v2
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Check typecript
        run: bun typecheck
      
      - name: Check format
        run: bun run format

      - name: Check linting
        run: bun run lint

  tests:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup bun v2
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install
      
      - name: Build Packages
        run: bun run build:packages

      - name: Run Tests
        run: bun run test